### PR TITLE
Cache compiled contracts

### LINKED ISSUE #713: Investigate contract precompilation for testing
### Feature Request

.

### PR DESCRIPTION
**Pull request by drknzz**
Closes #713

## Introduced changes

- Cache `compiled_contracts/` directory with `contracts/` directory hash ⚡ 

##

- [ ] This PR contains breaking changes

### CODE REVIEW

**Review by war-in — APPROVED** [review]
Nice 🔥 Two questions:
1. Do you know for how long the compiled contracts are cached? 
2. What if there is a new contract which was not compiled earlier?
    - commit changes and run tests
    - commit the new contract
    - will it be compiled or not?

**Comment by drknzz** [comment]
> 1. Do you know for how long the compiled contracts are cached?
 
I think it's 7 days.

> 2. What if there is a new contract which was not compiled earlier?
>    
>    * commit changes and run tests
>    * commit the new contract
>    * will it be compiled or not?

The files in `contracts` directory are hashed together, so if a new file is added, the contracts will compile and create a new cache.

**Comment by war-in** [comment]
Perfect 🥇 Thanks!

**Review by cptartur — COMMENTED** [review]
Will it correctly recompile the contracts if their source code changes in the PR? 

Also let's have @THenry14 review this

**Comment by drknzz** [comment]
> Will it correctly recompile the contracts if their source code changes in the PR?

Yes, if the source code of any contract changed, the hash of the files would also change. So there would be a new cache generated.

**Review by THenry14 — APPROVED** [review]
:+1:

**Pull request merged**
