### PR TITLE
Fix result selector on Custom RPC call

### PR DESCRIPTION
**Pull request by ExoMonk**
### **Please check if the PR fulfills these requirements**
- [x] The formatter, linter, and tests all run without an error
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug Fix on Custom RPC call results -> `starknet_call`

* **What is the current behavior?** (You can also link to an open issue here)

Calling `starknet_call` will always result into a TypeError as we check twice "result" key

## **What is the new behavior (if this is a feature change)?**

`starknet_call` is now working.

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

## **Other information**

-

### CODE REVIEW

**Comment by Solpatium** [comment]
What RPC do you use?

**Comment by ExoMonk** [comment]
> What RPC do you use?

-> jsonRPC (Pathfinder API) using FullNodeClient

**Comment by Solpatium** [comment]
Which pathfinder version do you use?

**Comment by Solpatium** [comment]
We unwrap result in http client already, so we do it again in here. It means there is also an issue with tests/devnet. 
@cptartur please investigate

**Comment by Solpatium** [comment]
Tests passed before because devnet returns it this way: https://discord.com/channels/793094838509764618/928219862327754812/1016738446989082624. We'll need to create a PR to fix it.

**Comment by cptartur** [comment]
Devnet issue will be addressed once 0.10 support is released. Merging this PR now however

**Pull request merged**
