### PR TITLE
add cairo_version to execute to support cairo1 calls encoding

### LINKED ISSUE #1164: Support calldata encoding for account using cairo 1
### Feature Request

With the release and support of account using Cairo1.0 adding a new `execute_v2` to account.py is required in order to support them

### PR DESCRIPTION
**Pull request by CremaFR**
Closes #1164

## Introduced changes

- add cairo_version to execute to support cairo1 calls encoding

##

- [ ] This PR contains breaking changes

### CODE REVIEW

**Comment by drknzz** [comment]
Hey @CremaFR, thanks for contributing 🚀
Could you provide code of the account you used for this?

**Comment by CremaFR** [comment]
> Hey @CremaFR, thanks for contributing 🚀 Could you provide code of the account you used for this?

Hey! I used OZ implementation https://github.com/OpenZeppelin/cairo-contracts/blob/cairo-2/src/account/account.cairo

And a test transaction with a multicall using my changes to show that calldata are not separated anymore
 https://goerli.voyager.online/tx/0x1629061102ff83ed6ba03ba72256077724634f535050529c36b2de4420f3619

**Comment by tomek0123456789** [comment]
Hello, great to see a contribution to starknet.py! Regarding the pull request, to serialize calldata for calls we use own serializers like in Cairo0 methods and we'd like to reuse them here, too. You can take your time and dig through our code to know how to use them or we can do it for you. Which option do you prefer?

**Comment by CremaFR** [comment]
> Hello, great to see a contribution to starknet.py! Regarding the pull request, to serialize calldata for calls we use own serializers like in Cairo0 methods and we'd like to reuse them here, too. You can take your time and dig through our code to know how to use them or we can do it for you. Which option do you prefer?

I've done the modifications, you're right it's better this way :)

**Comment by CremaFR** [comment]
> Well done 👌 One last thing before merging - I think replacing the additional `_v2` methods with a flag `cairo_version: int = 0` in `execute` and propagating it down to `_prepare_invoke`, in which there would be some if statements deciding which serializer to use, would be a bit better of an interface.

Done :)

**Pull request merged**
