### PR TITLE
chore: upgrade web.py and adjust supported python 3.7 range

### PR DESCRIPTION
**Pull request by unparalleled-js**
### **Please check if the PR fulfills these requirements**
- [ ] The formatter, linter, and tests all run without an error
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
update web3.py

* **What is the current behavior?** (You can also link to an open issue here)
fixes: #91 

## **What is the new behavior (if this is a feature change)?**
Using latest web3.py

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
The user may need to upgrade any logic related to older web3.py (though I am not sure what that would be, likely, it will be dealing with dependency related issues).

## **Other information**
I am not sure how to test locally because I think the `development` branch is assuming unreleased changes to `cairo-lang`; correct me if I am wrong, please. I have not figured out how to get a working development environment for `cairo-lang` (and I really don't need to, for the most part).

### CODE REVIEW

**Comment by unparalleled-js** [comment]
@Arcticae Do you have any thoughts on this one?
I am nervous with web3.py in general, as it is a shared dependency often.

Python projects using starknet and etheruem together are likely going to need web3.py and getting these dependencies to agree on a version might be challenging.

**Comment by unparalleled-js** [comment]
I did some digging and found out `web.py` needed to adjust their python dependency support: https://github.com/ethereum/web3.py/issues/2378

So, technically the latest `web.py` requires python `>=3.7.2`.

I think `Starknet-Py` should also, as most people use the latest minor in their major series, like python `3.7.12` if they are using python `3.7`, and there are real flaws with these version as well, which is why `ipfshttpclient` does not support them: https://github.com/ipfs-shipyard/py-ipfs-http-client/blob/master/pyproject.toml#L15-L23

Thus, I was able to create lock file by bumping said python version!

**Comment by unparalleled-js** [comment]
@Arcticae I believe I have found the magical range.

Testing I have done:

I ran the following commands in this order and there were no errors:

```bash
poetry lock
poetry install --extras docs
poetry install --extras eth-tester
poetry install --no-dev
poetry install
```

**Comment by Arcticae** [comment]
@unparalleled-js Thank you for your contribution!

**Pull request merged**
