### PR TITLE
New library structure

### LINKED ISSUE #347: Move contents `client_models` to `net.models`, deprecate `client_models`.
**Is your feature request related to a problem? Please describe.**

Refactor starknet.py so all our client related models are in `net.models` module.

**Describe the solution you'd like**

Move contents of `client_models.py` to separate files in `net.models` and deprecate it.

**Describe alternatives you've considered**

none

**Additional context**

n/a

### LINKED ISSUE #475: Remove imports in __init__ for modules
**Is your feature request related to a problem? Please describe.**
Importing files in __init__ can cause cyclic imports.

**Describe the solution you'd like**
Deprecate them and remove them after some time.

**Describe alternatives you've considered**
Leaving it as it is now.

**Additional context**
https://github.com/software-mansion/starknet.py/pull/471#discussion_r1000403597

### LINKED ISSUE #562: Propose a new structure of the library
### Feature Request

We should create a example structure tree of the library before we proceed with any eventual refactors of the package.

### PR DESCRIPTION
**Pull request by cptartur**
Closes #347
Closes #475
Closes #562

## Introduced changes

This is a draft for new library structure (attempt 3 😅).

##

- [ ] This PR contains breaking changes

### CODE REVIEW

**Comment by war-in** [comment]
I love the idea, but unfortunately, our users would be terrified by all these changes. We can rebuild our file structure once `Regenesis` happens

**Comment by cptartur** [comment]
Agreed, I'll think leave this open for now though.

**Comment by drknzz** [comment]
Please also change `starknet_py/tests/e2e/...` to `starknet_py/tests/...` in this PR 🙏 🙏 🙏

**Comment by cptartur** [comment]
This is blocked until at least after StarkNet 0.11.0

**Pull request closed without merging**
