### PR TITLE
Make dependencies for Ledger support optional

### PR DESCRIPTION
**Pull request by droserasprout**
## Introduced changes

`ledgerwallet` and `bip-utils` dependencies made optional. To use `LedgerSigner` the package needs to be installed with `-E ledger`.

These two libraries require lots of cryptography dependencies that significantly increase size of the virtualenv, Docker images, increase installation time and require compilation on many platforms.

`LateException` helper ensures that `ImportError` exception is raised only when Ledger code is actually used. Lazy imports could in addition improve import times, but require much more code changes.

## Breaking changes

Existing users will need to add `ledger` extra to dependencies after the update. 

## Bonus: workaround

If you're dealing with the same issues, found this PR, and it's still open, here's how to override dependencies in pyproject.toml with PDM package manager. Unfortunately, Poetry doesn't support such tricks.

```toml
[tool.pdm.resolution]
excludes = ["bip-utils", "ledgerwallet"]
```

### CODE REVIEW

**Comment by enitrat** [comment]
great, we were stuck because of compatibility issues because of this.

**Comment by franciszekjob** [comment]
@droserasprout thanks for the PR! It  looks good, will review it tomorrow :)

**Comment by franciszekjob** [comment]
@droserasprout Could you please fix linting?

**Comment by droserasprout** [comment]
There are multiple `poetry install` calls in the `checks.yml` workflow. I'm not sure which ones require extras, so added everywhere just in case.

**Comment by franciszekjob** [comment]
Ok, no worries. Will review it right after #1481 is merged, because this way "Tests" job in your PR will not be breaking.

**Comment by franciszekjob** [comment]
@droserasprout at first glance PR looks good, and passes tests (without network tests because env variables are not set).
However, we need to wait once https://github.com/software-mansion/starknet.py/issues/1473 is completed as it may changes `LedgerSigner` implementation. Will keep you updated.

**Review by franciszekjob — COMMENTED** [review]
Looking good 👍 
I think that we need to install Ledger extra using `poetry install -E ledger` only in `Tests` job (ledger is tested only there), in the rest it can be removed. Could you check it please @droserasprout ?

**Comment by droserasprout** [comment]
Done. I've updated a couple of section headers to make SETUP PYTHON part more copypastable.

**Comment by franciszekjob** [comment]
I think it would be better to address it in separate PR. Could you please just keep changes related to optional ledger installation (in `checks.yml` file) and open other PR for cleanup changes?

**Review by franciszekjob — APPROVED** [review]
lgtm

**Pull request merged**
