### PR TITLE
feat: add codespell linter workflow for CI & fix typos

### LINKED ISSUE #1228: feat: add codespell linter workflow for CI
### Feature Request

Codespell linter tool is very important for code and system quality, especially for enhancing docs readability.  

So I want to add codespell linter workflow for CI.

### PR DESCRIPTION
**Pull request by xiaolou86**
Closes #1228

## Introduced changes
1. Add codespell linter workflow for CI.
2. Fix typos.

##

- [x] This PR contains breaking changes

the api `starknet_py.utils.contructor_args_translator` changed to `starknet_py.utils.constructor_args_translator`, because of fixing typo error contructor_args_translator -> constructor_args_translator

### CODE REVIEW

**Review by ddoktorski — CHANGES_REQUESTED** [review]
The same comment as [here](https://github.com/software-mansion/scarb/pull/923). We are fine with accepting typo fixes, but we don't want to include this into our workflow. Please revert changes in `checks.yml` file.

**Comment by xiaolou86** [comment]
@ddoktorski That's all right. Thank you very much.

**Comment by xiaolou86** [comment]
@ddoktorski I have reverted changes in checks.yml file.

**Comment by ddoktorski** [comment]
@xiaolou86 
Thanks! Could you only resolve conflicts with `development` branch? Then it should pass all tests and we can merge it :)

**Comment by xiaolou86** [comment]
@ddoktorski Sure, I have resolved conflicts with development branch.

**Review by ddoktorski — APPROVED** [review]
Thanks :)

_Note: Failing tests due to unset env variables for networks in the fork repository that are used in checks.yml workflow_

**Pull request merged**
